module.exports = Object.freeze({
    VALID_EMAIL_VALUE: 'valid@valid.com',
    INVALID_EMAIL_VALUE: 'invalid',
    EMPTY_STRING_VALUE: '',
    VALID_STRING_VALUE: 'valid',
    API_SEND_ROUTE: '/api/send',
    EMAIL_SEPERATOR: ',',
    INVALID_EMAIL_MESSAGE: 'Invalid email provided: ',
    NO_RECIPIENTS_MESSAGE: 'No recipients provided',
    NO_SUBJECT_MESSAGE: 'No subject provided',
    NO_CONTENT_MESSAGE: 'No content provided',
    NO_HTML_MESSAGE: 'No html provided',
    SUCCESS: 'success',
    FAIL: 'fail',
    EMAILS_SENT_MESSAGE: 'Emails Sent!',
    INVALID_ACTION_MESSAGE: 'Invalid Action',
    SEND_ACTION: 'send',
    RECIPIENTS_PARAM: 'recipients',
    SUBJECT_PARAM: 'subject',
    HTML_PARAM: 'html',
    CONTENT_PARAM: 'content',
    EMAIL_PARAM: 'email',
    SENDING_EMAIL_ADDRESS: 'app163557149@heroku.com'
});